### PR TITLE
Update zeta to use latest libbpf

### PR DESCRIPTION
**Pull request by kiran1048**
The submodule libbpf is pulled to get the latest commit to be used in zeta.

### CODE REVIEW

**Comment by liangbin-pub** [comment]
Please make passes unit test (through build.sh debug) and E2E ping test with ACA before merge

**Comment by phudtran** [comment]
I believe the issue here is actually with travis.
I remember Kiran saying that the compilation passed with the kernel updated to 5.10.
However, the travis-ci VM's are most likely on an older kernel version. 
Which is probably why the tests failed (due to compilation failure)
From Travis
```
Scanning dependencies of target test_dmn
471[ 10%] Building C object src/CMakeFiles/test_dmn.dir/rpcgen/trn_rpc_protocol_xdr.c.o
472[ 13%] Building C object src/CMakeFiles/test_dmn.dir/rpcgen/trn_rpc_protocol_svc.c.o
473[ 15%] Building C object src/CMakeFiles/test_dmn.dir/dmn/test/test_dmn.c.o
474In file included from /mnt/host/code/src/dmn/trn_transit_xdp_usr.h:46,
475                 from /mnt/host/code/src/dmn/trn_transitd.h:31,
476                 from /mnt/host/code/src/dmn/test/test_dmn.c:32:
477/mnt/host/code/build/lib/usr/include/bpf/bpf.h:244:6: error: ISO C forbids forward references to 'enum' types [-Werror=pedantic]
478  244 | enum bpf_stats_type; /* defined in up-to-date linux/bpf.h */
479      |      ^~~~~~~~~~~~~~
480/mnt/host/code/build/lib/usr/include/bpf/bpf.h:245:38: error: ISO C forbids forward references to 'enum' types [-Werror=pedantic]
481  245 | LIBBPF_API int bpf_enable_stats(enum bpf_stats_type type);
482      |                                      ^~~~~~~~~~~~~~
483cc1: all warnings being treated as errors
484src/CMakeFiles/test_dmn.dir/build.make:124: recipe for target 'src/CMakeFiles/test_dmn.dir/dmn/test/test_dmn.c.o' failed
485make[2]: *** [src/CMakeFiles/test_dmn.dir/dmn/test/test_dmn.c.o] Error 1
486CMakeFiles/Makefile2:974: recipe for target 'src/CMakeFiles/test_dmn.dir/all' failed
487make[1]: *** [src/CMakeFiles/test_dmn.dir/all] Error 2
488make: *** [all] Error 2
489Makefile:113: recipe for target 'all' failed
490The command "./build.sh debug" exited with 2.
```

Is it time to move to Jenkins?  @liangbin-pub 💇

**Comment by liangbin-pub** [comment]
@phudtran I remember I have added kernel upgrade to Travis pre-script, so the VM should have correct kernel header and lib for build container.
Ideally we want to move to Jenkins

**Comment by kiran1048** [comment]
I am closing this PR as some more changes have gone in to libbfp and alcore since PR was opened. A new private branched cut from latest main will be created and libbpf updates will be made into it.

**Pull request closed without merging**
